[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GeometricIntegrators = "dcce2d33-59f6-5b8d-9047-0defad88ae06"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RungeKutta = "fb486d5c-30a0-4a8a-8415-a8b4ace5a6f7"
SimpleSolvers = "36b790f5-6434-4fbe-b711-1f64a1e2f6a2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
